blog:
  build: ghost/
  environment:
    VIRTUAL_HOST: "192.168.99.100"
    NODE_ENV: "production"
    PUBLIC_URL: "https://192.168.99.100"
  volumes:
    - /content/data:/app/content/data
    - /content/images:/app/content/images
    - /content/themes:/app/content/themes
    - /content/apps:/app/content/apps
  ports:
    - "80:2368"
  restart: always
