blog:
  build: ghost/
  environment:
    VIRTUAL_HOST: "dockercluster.tk"
    NODE_ENV: "production"
    PUBLIC_URL: "http://dockercluster.tk"
  volumes:
    - /content/data:/app/content/data
    - /content/images:/app/content/images
    - /content/themes:/app/content/themes
    - /content/apps:/app/content/apps
  ports:
    - "3003:3003"
  restart: always
