blog:
  build: ghost/
  environment:
    VIRTUAL_HOST: "domainname.com"
    NODE_ENV: "production"
    PUBLIC_URL: "https://www.domain.com"
  volumes:
    - /host_directory/data:/app/content/data
    - /host_directory/images:/app/content/images
    - /host_directory/themes:/app/content/themes
  ports:
    - "80:2368"
  restart: always
   
